/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import controle.Controle;
import entidades.Comentario;
import entidades.Filme;

/**
 *
 * @author fatec
 */
public class AdicionarComentario extends javax.swing.JFrame {
    
    private Controle controle = new Controle();
    Filme selectedFilme;
    
    /**
     * Creates new form AdicionarComentario
     */
    public AdicionarComentario(Filme filme) {
        initComponents();
        
        selectedFilme = filme;
        
        changePageName();
    }
    
    private void changePageName () {
        txtNomeFilme.setText(selectedFilme.getTitulo());
    }
    
    private boolean areFieldsValid () {
        String comentario = inpComentario.getText();
        String nota = inpNota.getText();
        String usuario = inpUsuario.getText();
        
        String[] allFields = {comentario, nota, usuario};
        
        return !anyEmpty(allFields);
    }
    
    private boolean anyEmpty (String[] texts) {
        for (String text: texts) {
            if (text.equals("")) {
                return true;
            }
        }
        return false;
    }
    
    private void createComentario () {
        String comentarioText = inpComentario.getText();
        Double nota = Double.valueOf(inpNota.getText());
        String usuario = inpUsuario.getText();
        int filme = selectedFilme.getIdFilme();
        
        Comentario comentario = new Comentario(comentarioText, nota, usuario, filme);
        
        controle.salvarComentario(comentario);
    }
    
    private void closeWindow () {
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        inpNota = new javax.swing.JTextField();
        inpComentario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inpUsuario = new javax.swing.JTextField();
        btnComentar = new javax.swing.JButton();
        cadastroTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeFilme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Nota");

        inpNota.setToolTipText("Insira o diretor do filme");
        inpNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNotaActionPerformed(evt);
            }
        });

        inpComentario.setToolTipText("Insira o ano do filme");
        inpComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpComentarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Usuario");

        inpUsuario.setToolTipText("Insira o país do filme");
        inpUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpUsuarioActionPerformed(evt);
            }
        });

        btnComentar.setText("ENVIAR COMENTARIO");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        cadastroTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastroTitle.setText("DEIXE UM COMENTARIO");

        jLabel2.setText("Comentario");

        txtNomeFilme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNomeFilme.setText("Nome do filme");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inpComentario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpNota, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComentar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cadastroTitle)
                .addGap(40, 40, 40)
                .addComponent(txtNomeFilme)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(btnComentar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNotaActionPerformed

    private void inpComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpComentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpComentarioActionPerformed

    private void inpUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpUsuarioActionPerformed

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        // TODO add your handling code here:
        if (areFieldsValid()) {
            createComentario();
            closeWindow();
        }
    }//GEN-LAST:event_btnComentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarComentario(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JLabel cadastroTitle;
    private javax.swing.JTextField inpComentario;
    private javax.swing.JTextField inpNota;
    private javax.swing.JTextField inpUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel txtNomeFilme;
    // End of variables declaration//GEN-END:variables
}
