/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import controle.Controle;
import entidades.Filme;
import entidades.Genero;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author fatec
 */
public class Principal extends javax.swing.JFrame {
    
    private Controle controle = new Controle();
    private LinkedList<Genero> listaGenero = new LinkedList<>();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        updateGeneros();
    }

    private void updateGeneros () {
        listaGenero.addAll(controle.consultarGeneros());
        cmbGenero.setModel(new DefaultComboBoxModel(listaGenero.toArray()));
    }
    
    private boolean areFieldsValid () {
        String titulo = inpTitulo.getText();
        String ano = inpAno.getText();
        String diretor = inpDiretor.getText();
        String pais = inpPais.getText();
        
        String[] allFields = {titulo, ano, diretor, pais};
        
        return !anyEmpty(allFields);
    }
    
    private boolean anyEmpty (String[] texts) {
        for (String text: texts) {
            if (text.equals("")) {
                return true;
            }
        }
        return false;
    }

    private void openAddGenero () {
        new AdicionarGenero().setVisible(true);
    }
    
    private void openListaFilmes () {
        new ListaFilmes().setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        cadastroTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inpTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inpAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inpDiretor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inpPais = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCriarGenero = new javax.swing.JButton();
        cmbGenero = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnLista = new javax.swing.JButton();

        jLabel3.setText("Ano");

        jTextField3.setToolTipText("Insira o ano do filme");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cadastroTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastroTitle.setText("CADASTRO DE FILMES");

        jLabel1.setText("Título");

        inpTitulo.setToolTipText("Insira o título do filme");
        inpTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTituloActionPerformed(evt);
            }
        });

        jLabel2.setText("Ano");

        inpAno.setToolTipText("Insira o ano do filme");
        inpAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpAnoActionPerformed(evt);
            }
        });

        jLabel4.setText("Diretor");

        inpDiretor.setToolTipText("Insira o diretor do filme");
        inpDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpDiretorActionPerformed(evt);
            }
        });

        jLabel5.setText("País");

        inpPais.setToolTipText("Insira o país do filme");
        inpPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpPaisActionPerformed(evt);
            }
        });

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCriarGenero.setText("CRIAR GÊNERO");
        btnCriarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarGeneroActionPerformed(evt);
            }
        });

        jLabel6.setText("Gênero");

        btnLista.setText("LISTA DE FILMES");
        btnLista.setToolTipText("");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpTitulo)
                    .addComponent(inpAno)
                    .addComponent(inpDiretor)
                    .addComponent(inpPais)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCriarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cadastroTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cadastroTitle)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpTituloActionPerformed

    private void inpAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpAnoActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void inpDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpDiretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpDiretorActionPerformed

    private void inpPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpPaisActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        if (areFieldsValid()) {
            System.out.println("Campos válidos :D");
        } else {
            System.out.println("Campos inválidos D:");
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCriarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarGeneroActionPerformed
        openAddGenero();
    }//GEN-LAST:event_btnCriarGeneroActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        openListaFilmes();
    }//GEN-LAST:event_btnListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCriarGenero;
    private javax.swing.JButton btnLista;
    private javax.swing.JLabel cadastroTitle;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JTextField inpAno;
    private javax.swing.JTextField inpDiretor;
    private javax.swing.JTextField inpPais;
    private javax.swing.JTextField inpTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
